global using System;
global using System.Collections.Generic;
global using System.CommandLine;
global using System.IO;
global using System.Linq;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using Common.Configuration;
global using Common.Constants;
global using Common.Contracts;
global using Common.Logging;
global using Common.CliProtocol;
global using Common.Plugins;
global using Common.Tools;
global using Service.Json.Contracts;
global using Service.Json;
global using McpProtocol.Contracts;
global using MemoryCli.Commands;
global using MemoryCli.Services;
global using MemoryCli.Validation;
global using static Common.Constants.ConstantManager;
global using static Common.Constants.ConstantManager.Commands;
