using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;

namespace CliCommandGenerator;

[Generator]
public sealed class HostCommandTableGenerator : IIncrementalGenerator
{
    private const string HandlerAttributePattern = @"\[CliCommandHandler\(""([^""]+)"",\s*""([^""]+)""[^]]*?\]";
    private const string CommandAttributePattern = @"\[CliCommand\(""([^""]+)"",\s*Description\s*=\s*""([^""]+)""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pluginSourceFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith("CommandHandler.cs", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => (Path: file.Path, Text: file.GetText(ct)?.ToString() ?? ""))
            .Collect();

        context.RegisterSourceOutput(pluginSourceFiles, static (ctx, files) => GenerateCommandTable(ctx, files));
    }

    private static void GenerateCommandTable(SourceProductionContext context, ImmutableArray<(string Path, string Text)> files)
    {
        var plugins = new List<PluginEntry>();

        foreach (var file in files)
        {
            var plugin = ParsePluginSource(file.Path, file.Text);
            if (plugin != null)
                plugins.Add(plugin);
        }

        if (plugins.Count == 0) return;

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("internal static class CommandTable");
        sb.AppendLine("{");

        GenerateCommandData(sb, plugins);
        sb.AppendLine();
        GeneratePrintTable(sb, plugins);

        sb.AppendLine("}");

        context.AddSource("CommandTable.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static PluginEntry? ParsePluginSource(string filePath, string source)
    {
        var handlerMatch = Regex.Match(source, HandlerAttributePattern);
        if (!handlerMatch.Success) return null;

        var pluginName = handlerMatch.Groups[1].Value;
        var displayName = SnakeToPascal(pluginName);

        var commands = new List<CommandEntry>();
        var commandMatches = Regex.Matches(source, CommandAttributePattern);

        foreach (Match match in commandMatches)
        {
            var commandName = match.Groups[1].Value;
            var description = match.Groups[2].Value;
            commands.Add(new CommandEntry(commandName, description));
        }

        return commands.Count == 0 ? null : new PluginEntry(displayName, pluginName, commands);
    }

    private static string SnakeToPascal(string snake)
    {
        var parts = snake.Split('_');
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0) continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            sb.Append(part.AsSpan(1));
        }
        return sb.ToString();
    }

    private static void GenerateCommandData(StringBuilder sb, List<PluginEntry> plugins)
    {
        sb.AppendLine("    internal static readonly (string Plugin, string Command, string Description)[] AllCommands =");
        sb.AppendLine("    [");

        foreach (var plugin in plugins)
        {
            foreach (var cmd in plugin.Commands)
            {
                sb.AppendLine($"        (\"{plugin.DisplayName}\", \"{cmd.Name}\", \"{EscapeString(cmd.Description)}\"),");
            }
        }

        sb.AppendLine("    ];");
    }

    private static void GeneratePrintTable(StringBuilder sb, List<PluginEntry> plugins)
    {
        var maxPluginLen = plugins.Max(p => p.DisplayName.Length);
        var maxCmdLen = plugins.SelectMany(p => p.Commands).Max(c => c.Name.Length);

        sb.AppendLine("    internal static void PrintTable(System.Action<string> writeLine)");
        sb.AppendLine("    {");

        foreach (var plugin in plugins)
        {
            sb.AppendLine($"        writeLine(\"\");");
            sb.AppendLine($"        writeLine(\"[{plugin.DisplayName}]\");");

            foreach (var cmd in plugin.Commands)
            {
                var paddedPlugin = plugin.DisplayName.PadRight(maxPluginLen);
                var paddedCmd = cmd.Name.PadRight(maxCmdLen);
                sb.AppendLine($"        writeLine(\"  {paddedPlugin} - {paddedCmd} - {EscapeString(cmd.Description)}\");");
            }
        }

        sb.AppendLine();
        var totalCommands = plugins.Sum(p => p.Commands.Count);
        sb.AppendLine($"        writeLine(\"\");");
        sb.AppendLine($"        writeLine(\"  Total: {plugins.Count} plugins, {totalCommands} commands\");");
        sb.AppendLine("    }");
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private sealed record PluginEntry(
        string DisplayName,
        string PluginName,
        List<CommandEntry> Commands
    );

    private sealed record CommandEntry(
        string Name,
        string Description
    );
}
