global using System;
global using System.Collections.Generic;
global using System.CommandLine;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading;
global using System.Threading.Tasks;
global using Common.Configuration;
global using Common.Constants;
global using Common.Logging;
global using Common.CliProtocol;
global using FileReaderCli.Commands;
global using FileReaderCli.Services;
global using Common.Contracts.Models;
global using Common.Json;
global using Common.Contracts;
global using FileLock;
global using FileLock.Contracts;
global using McpProtocol.Contracts;
global using static Common.Constants.ConstantManager;
global using static Common.Constants.ConstantManager.Commands;
